### ISSUE TITLE
No Image in PDF

### ISSUE THREAD

**Issue by DanteFan24** [DarylBuckle/dnd-character-sheets#1]
So I created a character and place an image in the respective field but that image doesn't move into the pdf nor printing.

**Comment by DarylBuckle** [comment]
Hi DanteFan24,

Thanks for creating this issue.

A number of browsers don't normally print background images by default, but have options to enable this. For example, Chrome has the "Background graphics" option on the print preview (shown below), enabling this should print the images and any other background graphics. Safari also has a similar option. I'm not sure about other browsers.

![image](https://user-images.githubusercontent.com/15156674/111912033-bb125880-8a5f-11eb-8331-eb657bc85065.png)

I'll add something to the css which should suggest to most browsers to print this all the time by default, to make this step unnecessary.

All the best,
Daryl
