### ISSUE TITLE
A blank page in printing?

### ISSUE THREAD

**Issue by xuhangc** [DarylBuckle/dnd-character-sheets#4]
Hi, ty for this amazing character sheets.
I found that there would be an extra blank sheet at the end when I was trying to printing. Is it intended?

**Comment by DarylBuckle** [comment]
Hi xuhangc, thanks for raising this issue.

It's not intended that there is an extra blank sheet when printing. It is likely an issue that occurs on particular browsers.

Can I ask what browser and OS you are using to print the sheet so that I may reproduce the issue?

**Comment by xuhangc** [comment]
> Can I ask what browser and OS you are using to print the sheet so that I may reproduce the issue?

I am using Windows11 and Edge Beta 94.0.992.38. It could be a compatibility issue. I am also not sure.

**Comment by xuhangc** [comment]
fixed now, ty.
